export default {
  validate: false,
  teamMembers: null,
  salesRepsList: null,
  companiesList: null,
  serviceCompaniesList: null,
  draftBidsList: null,
  bidsLists: [],
  itemBidData: null,
  bidData: {
    title: '',
    type: '',
    regions: '',
    dueDate: '',
    dueTime: '',
    qAndAEnabled: '',
    bidDescriptions: [{ body: '' }],
  },
  attachData: null,
  draftTime: null,
  newSupplier: [],
  submittedBids: [],
  supplierBid: null,
  lineItemsComplete: false,
  bidDetailsComplete: false,
  alertDeleteBidSuccess: false,
  alertDeleteBidError: false,
  bidViewData: null,
  viewBidError: false,
  invitedSuppliers: null,
  invitedTeamMembers: null,
  bidlines: null,
  attachement: null,
  questions: null,
  bidSerial: null,
  invitedSuppliersData: null,
  bidIntent: null,
  supplierAttachment: [],
  userType: null,
  intentId: null,
  isBidSubmitted: false,
  qAndA: [],
  draftBidData: null,
  draftBidsListId: null,
};
