name: Dev - Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm i
      - name: Create Env
        run: |
          touch .env
          cat .env
      - name: Build
        run: npm run build
      - name: Upload Dist Folder
        uses: actions/upload-artifact@v3
        with:
          name: Dist
          path: dist/
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Download Dist Artifact
        uses: actions/download-artifact@v3
        with:
          name: Dist
          path: dist/
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          deliverables: 'dev.yaml'